### PR TITLE
WIP SPIDER: Zoning Board of Appeals

### PR DESCRIPTION
**Pull request by milti**

### CODE REVIEW

**Comment by jim** [comment]
Hi @milti! Thanks for the submission. I updated the pull request title to indicate that this is a work in progress.

**Comment by eads** [comment]
This has some direct bearing on #56. @milti said she was willing to hand it off, so I'm wondering if @jim, @r-wei, or @bonfirefan could take a look and come up with a way to knock off a bunch of agencies in one fell swoop. 

It's worth looking at https://www.cookcountyil.gov/calendar?&page=1 -- there might be a way to crawl that and determine agency information.

Another way might be looping over a set of IDs and hitting all the "agency-events" pages, e.g. https://www.cookcountyil.gov/agency-events/2192 ...

**Comment by r-wei** [comment]
It looks like all the ZBA events are in the past... https://www.cookcountyil.gov/agency-events/2192

Maybe the main calendar (https://www.cookcountyil.gov/calendar) is the only thing we need to look at for future events. It looks like agency events like for the forest preserve are on the main calendar. I think Shinda was working on the main calendar too.

**Comment by bonfirefan** [comment]
It looks like there is a legistar website for Cook County: https://cook-county.legistar.com/Calendar.aspx 
We could likely use the same legsitar scraping tools used in Councilmatic that scraped the city clerk site. 
https://github.com/datamade/chi-councilmatic

**Comment by bonfirefan** [comment]
False hope, sorry, the legistar site is only the board of commissioners.

**Comment by jim** [comment]
Looks like these events were picked up from another site they were posted on.

**Pull request closed without merging**
