### PR TITLE
101 spider cclba

### PR DESCRIPTION
**Pull request by dcldmartin**
Finally got this into shape!

### CODE REVIEW

**Comment by eads** [comment]
Hey @dcldmartin, you should add some tests!

**Comment by dcldmartin** [comment]
@eads Not sure what the failure here is about. The challenge was my spider is running iterated AJAX requests, so I modified 'utils.py' to look for a JSON object (the response format from the server) and return a TextResponse object instead. Not sure if I did that quite right.

**Comment by r-wei** [comment]
Hey @dcldmartin , it looks like your tests are passing on Travis CI. The failing checks are just some unused imports: 

./documenters_aggregator/spiders/cclba.py:8: 'datetime.datetime' imported but unused
./documenters_aggregator/spiders/cclba.py:10: 'time' imported but unused
./documenters_aggregator/spiders/cclba.py:11: 'lxml.html.fromstring' imported but unused
./documenters_aggregator/spiders/cclba.py:12: 'cssselect' imported but unused
./tests/test_cclba.py:1: 'pytest' imported but unused
./tests/test_cclba.py:2: 'scrapy' imported but unused
./tests/test_cclba.py:7: 'json' imported but unused
./tests/test_cclba.py:8: 'datetime as dt' imported but unused
./tests/test_cclba.py:9: 'pytz' imported but unused

**Comment by dcldmartin** [comment]
Cool, thanks @r-wei !

**Comment by eads** [comment]
@dcldmartin as soon as you remove the unused imports, I'll give this the 👍 or @r-wei can as well

**Comment by dcldmartin** [comment]
Done!

**Pull request merged**
