### PR TITLE
moved genspider html files to tmp/

### PR DESCRIPTION
**Pull request by r-wei**
resolves 46 according to Jim's suggestion. If the tests pass, then the html files created from genspider get moved to files/tmp/  (It doesn't make sense to move the files if the tests don't pass because then something went wrong in downloading or naming the files.)

### CODE REVIEW

**Comment by jim** [comment]
Do you think it would make sense to just delete the files instead of moving them? Do we need them for anything after the test runs?

**Comment by eads** [comment]
++ @jim -- seems cleanest just to delete when done to me.

**Comment by r-wei** [comment]
sounds good. I updated the code to delete them.

**Comment by eads** [comment]
whoops, closes #46

**Pull request merged**
