### PR TITLE
107 spider cit

### PR DESCRIPTION
**Pull request by dcldmartin**
This one just had dates - no meeting times - and no additional info. Not sure how useful it is....

### CODE REVIEW

**Comment by eads** [comment]
Looks like there's a bunch of imports that need to be removed before tests pass. 

@diaholliday what do you think we should do about the missing times?

**Comment by diaholliday** [comment]
Can we have them all say 10a? Looks like the Land Bank always meets at the same time. You can see the times and minutes when you click further into the calendar notice.

**Comment by dcldmartin** [comment]
I think you're looking at the wrong one :) The infrastructure trust doesn't
have any times on their meetings as far as I can see on the site:

http://chicagoinfrastructure.org/public-records/scheduled-meetings/

**Comment by diaholliday** [comment]
Ah yes, you are correct. I was looking at the Land Bank. But it looks like the Trust does also meet (mostly) at 10a, though it's not consistent from meeting to meeting: http://chicagoinfrastructure.org/press/blog/

**Comment by dcldmartin** [comment]
Interesting.... And scraping the blog might be a little tough. It's a
little less consistently structured. I could just point to the blog page in
an additional field to check for time/location.

Though, if the date on the blog post is to be believed, the notice for
rescheduling the last meeting was given after the meeting happened. And
notice was given of the previous meeting only a couple days in advance. If
the point of this info is to plan ahead this may not be the best source.

**Comment by r-wei** [comment]
Something strange is going on with this pull request. The travis ci check is failing because of a failed test in the cpb spider, but the cpb.py and test_cpb.py are not in the 107-spider-cit branch... @eads , can you rebuild travis?

**Comment by eads** [comment]
Man, being sick really caused me to miss a lot of stuff. This all looks good.

**Pull request merged**
