### PR TITLE
Template updates

### PR DESCRIPTION
**Pull request by joshuarrrr**
I ran into some errors and failing tests that can be fixed in the templates.

### CODE REVIEW

**Comment by r-wei** [comment]
Thanks for doing this! These bugs have been, well, bugging me. :P 

I'd like to change line 14 in templates/spider.tmpl to use the start_urls argument from genspider (if present), and the domain (without the leading http://) otherwise. And we should also change tests/test_tasks.py so that the tests pass. @joshuarrrr, do you want to take a crack at those? If not, would you be ok with me contributing to this branch?

**Comment by eads** [comment]
+1 to fixing tests in test_tasks. I wonder how to test to make sure future tweaks to the templates don't break syntax tests etc.

**Comment by joshuarrrr** [comment]
@r-wei I'll change line 14 and fix the tests.

**Comment by joshuarrrr** [comment]
@r-wei I fixed the failing tests and added support for start_urls.

But could you take a look? I'm don't have that much experience using Jinja to template out other Python files, and I imagine there's probably a cleaner way to do the logic.

I also just used the initial start_urls string input; it might be cleaner to use the parsed list instead.

**Comment by eads** [comment]
I'll review.

**Comment by r-wei** [comment]
Thanks @eads. There's some inconsistency in the code on the expected format of start_urls. I was expecting each url to start with http, and thus using `,http` to split the urls (in case there were non-escaped commas). Joshua has been removing the http's (because it's cleaner for the template?). I don't have strong opinions on which way to go.

**Pull request merged**
