### PR TITLE
Caps spider Chicago Police

### PR DESCRIPTION
**Pull request by csethna**
This is a completed spider which crawls the [Chicago Police Community Events Calendar](https://home.chicagopolice.org/get-involved-with-caps/all-community-event-calendars/), returns all the events which are publicly available via [CAPS miniproxy](https://home.chicagopolice.org/wp-content/themes/cpd-bootstrap/proxy/miniProxy.php?https://home.chicagopolice.org/get-involved-with-caps/all-community-event-calendars/). Results formatted to return data in [Open Civic Data Event Format](http://docs.opencivicdata.org/en/latest/data/event.html).

### CODE REVIEW

**Comment by eads** [comment]
Woot! Looks like you have a few unused imports though.

**Comment by csethna** [comment]
Hey David:

json gets called on line 27, pytz gets called on line 117, datetime gets used on line 118. Are there other imports you’re seeing which are unused? I’m happy to update and submit another PR.

-Cyrus

Cyrus Sethna
about.csethna.com

**Comment by r-wei** [comment]
Hey @csethna , it looks like json is used in the spider, but unused in documenters_aggregator/caps.py -- is this file needed? Also pytest is unused in tests/test_caps.py

I got this information from clicking on Details under where Travis CI shows failing checks.

**Comment by jim** [comment]
Hey @csethna, I merged master into your branch to bring it up to date with our other code. You can run `invoke runtests` to run all unit tests and syntax/style checkers. When there aren't any more warnings, we should be close to getting this merged in!

**Comment by diaholliday** [comment]
Hey all,
Just wanted to make sure I'm reading this right. Is this spider "done" but awaiting another check?

CC @csethna

**Pull request merged**
