### PR TITLE
add `long_name` property to all spiders

### PR DESCRIPTION
**Pull request by eads**
the acronyms are lovely and yet confusing! refs #94 

there's some stuff to figure out here, like how genspider should work with a long name, which also makes me think this should wait for #105

### CODE REVIEW

**Comment by eads** [comment]
So I'm thinking one of two options for `invoke genspider`:

Required option:

```
invoke genspider cpb "Chicago Police Board" http://...
```

Optional option:

```
invoke genspider cpd http:// -t "Chicago Police Board"
```

where the long name is optional and replaced by "cpb" or maybe "CPB" when generated.

What do yall think?

**Comment by joshuarrrr** [comment]
I would lean toward the required option.

**Comment by eads** [comment]
Unless someone objects, I think @joshuarrrr's instinct is good and we should just require it.

It isn't something you have to do a lot, and capturing that information up front is good to get out of the way at that point.

**Comment by r-wei** [comment]
Sounds good to me

**Pull request merged**
